### method ERROR
PUT http://localhost:8080

### earth
POST http://localhost:8080/earth

### Delete
DELETE http://localhost:8080/web/toma.txt

### get files
GET http://localhost:8080/files

### colors
GET   http://localhost:8080/colors

### archivo html
GET   http://localhost:8080/astronaut/toma.html

### alias
GET   http://localhost:8080/tomate/mas/otra/cosa.html


